// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using CoreDal.Repository;

namespace CoreDal.Migrations
{
    [DbContext(typeof(CoreDataContext))]
    [Migration("20171229051703_AddUser")]
    partial class AddUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreDal.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<long?>("UserDepartmentId");

                    b.HasKey("Id");

                    b.HasIndex("UserDepartmentId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CoreDal.UserDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<int>("Capacity");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("DeptNo");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("UserDepartment");
                });

            modelBuilder.Entity("CoreDal.User", b =>
                {
                    b.HasOne("CoreDal.UserDepartment", "UserDepartment")
                        .WithMany()
                        .HasForeignKey("UserDepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
